/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
    //未分类：
	"对敌方造成": "inflict on the enemy",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$\$/,
	/^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,

];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
	[/^(\d+) 物理伤害/, ' $1 Physical Damage'],
	[/^(\d+) 魔法伤害/, ' $1 Magic Damage'],
	
	[/^对敌方造成 (\d+) 物理伤害(\d+)次/, 'deal $1 Physical Damage to the enemy $2 times'],
	[/^对敌方造成 (\d+) 物理伤害/, 'inflict on the enemy $1 Physical Damage'],
	[/^增加 (\d+) 护甲/, 'get $1 Armor'],
	[/^恢复 (\d+) 血,获得 (\d+) 恢复/, 'restore $1 HP,get $2 Restoration'],
	[/^对敌方造成 (\d+) 魔法伤害/, 'inflict on the enemy $1 Magic Damage'],
	[/^先获得 (\d+) 智慧,再增加 (\d+) 体力, (\d+) 魔力/, 'gain $1 Wisdom first, then increase $2 Stamina, $3 Mana'],
	[/^恢复 (\d+) 魔力/, 'get $1 mana'],
	[/^获得 (\d+) 力量/, 'get $1 Strength'],
	[/^给敌方 (\d+) 中毒/, 'Poison the enemy $1'],
	[/^给敌方 (\d+) 感染,我方 (\d+) 感染/, 'Infects $1 the enemy and $2 you'],

	[/^消耗:(\d+) 血/, 'consume:$1 HP'],
	[/^消耗:(\d+) 魔力/, 'consume:$1 Mana'],
	[/^消耗:x 魔力/, 'consume:x Mana'],
	[/^消耗:(\d+) 体力/, 'consume:$1 Stamina'],
	[/^消耗:无/, 'consume:None'],
	
	[/^血量 (\d+) \/ (\d+)/, 'HP $1 / $2'],
	[/^魔力 (\d+) \/ (\d+)/, 'Mana $1 / $2'],
	[/^体力 (\d+) \/ (\d+)/, 'Stamina $1 / $2'],
	[/^攻击 (\d+)/, 'Damage $1'],
	
	[/^护甲 (\d+)/, 'Armor $1'],
	[/^(\d+)护甲/, '$1Armor'],
	[/^智慧 (\d+)/, 'Wisdom $1'],
	[/^(\d+)智慧/, '$1Wisdom'],
	[/^恢复 (\d+)/, 'Restoration $1'],
	[/^(\d+)恢复/, '$1Restoration'],
	[/^力量 (\d+)/, 'Strength $1'],
	[/^(\d+)力量/, '$1Strength'],
	[/^中毒 (\d+)/, 'Poison $1'],
	[/^(\d+)中毒/, '$1Poison'],
	[/^感染 (\d+)/, 'Infects $1'],
	[/^(\d+)感染/, '$1Infects'],
	
	[/^攻击/, 'attack'],
	[/^防御/, 'defense'],
	[/^治疗/, 'treat'],
	[/^魔法飞弹/, 'Magic Missile'],
	[/^魔力源泉/, 'Source Of Magic'],
	[/^冥想/, 'Meditation'],
	[/^连斩/, 'Continuous cutting'],
	[/^愤怒/, 'Angry'],
	[/^传染/, 'Contagion'],
	[/^病原体/, 'Pathogen'],
	
	[/^保存/, 'save'],
	[/^材质: 经典/, 'Theme: Classical'],
	[/^材质: 纯白/, 'Theme: Pure white'],
	[/^材质: 亮蓝/, 'Theme: Bright blue'],
	[/^材质: 海蓝/, 'Theme: Navy blue'],
	[/^材质: 游戏树特殊页面/, 'Theme: Classical'],
	[/^文字荧光: 开/, 'fluorescence: Open'],
	[/^文字荧光: 关/, 'The special page in The-Game-Tree' ],
	[/^返回游戏/, 'Return to game'],
	[/^返回/, 'Return'],
	[/^存档/, 'File'],
	[/^画面/, 'Frame'],
	[/^操作/, 'Operation'],
	[/^硬重置/, 'HardRest'],
	[/^软重置/, 'SoftRest'],
	[/^按住shift点击永久显示悬浮框: 开/, 'Tap the shift and click to display Suspension window foever: Open'],
	[/^按住shift点击永久显示悬浮框: 关/, 'Tap the shift and click to display Suspension window foever: Close'],
	
	[/^把鼠标对准我查看全属性/, 'Let your mouse here to check all the attribute'],
	[/^tip:你有5种不同的背景可以换(包括亮色),当前背景:/, 'tip:You have five kinds of backcolor to change(include Bright color),and now the backcolor is:'],
	[/^经典/, 'Classical'],
	[/^纯白/, 'Pure white'],
	[/^亮蓝/, 'Bright blue'],
	[/^海蓝/, 'Navy blue'],
	[/^QQ群:688646311\|左上角设置,信息,捐助\|右上角版本,图鉴,背包/, 'QQ group(A software in China):688646311|Upper left corner:setting,information and donation|Upper right corner:version,illustrated and backpacker'],
	[/^加载中/, 'LOADING'],
	[/^右上角分别是版本,图鉴,背包./, 'Upper left corner:setting,information and donation.'],
	[/^左上角分别是设置,信息,捐助./, 'Upper right corner:version,illustrated and backpacker.'],
	[/^QQ群:688646311/, 'QQ group:688646311'],
	[/^你的最高分是/, 'Your highest score is'],
	[/^你上次的得分是/, 'Last time your score is'],
	[/^你在关卡/, 'Now,you are in level'],
	[/^怪物会随着关卡提升越来越强/, 'The monster will become stronger and stronger with the levels you have pathed'],
	[/^牌库/, 'Card bank'],
]); 
